import { z } from "zod";
import { SceneSchema } from "./scene.validation";

export const LensSKUSchema = z.enum([
  "rgle_8smoke",
  "rgle_8brown",
  "rgle_8silverblue",
  "rgle_8blue",
  "rgle_8fire",
  "rgle_8green",
  "rgle_8purple",
  "rgle_8gold",
  "rgle_Psmoke",
  "rgle_Pbrown",
  "rgle_Pblue",
  "rgle_Psilverblue",
  "rgle_Pfire",
  "rgle_Pgreen",
  "rgle_Ppurple",
  "rgle_Pgold",
  "rgle_8Psmoke",
  "rgle_8Pbrown",
  "rgle_8Pblue",
  "rgle_8Psilverblue",
  "rgle_8Pfire",
  "rgle_8Pgreen",
  "rgle_8Ppurple",
  "rgle_8Pgold",
  "rgle_STRXsmoke",
  "rgle_THRXsmoke",
  "rgle_STPRXsmoke",
  "rgle_THPRXsmoke",
  "rgle_STRXblue",
  "rgle_THRXblue",
  "rgle_STPRXblue",
  "rgle_THPRXblue",
  "rgle_STRXsilverblue",
  "rgle_THRXsilverblue",
  "rgle_STPRXsilverblue",
  "rgle_THPRXsilverblue",
  "rgle_STRXfire",
  "rgle_THRXfire",
  "rgle_STPRXfire",
  "rgle_THPRXfire",
  "rgle_STRXgreen",
  "rgle_THRXgreen",
  "rgle_STPRXgreen",
  "rgle_THPRXgreen",
  "rgle_STRXpurple",
  "rgle_THRXpurple",
  "rgle_STPRXpurple",
  "rgle_THPRXpurple",
  "rgle_STRXgold",
  "rgle_THRXgold",
  "rgle_STPRXgold",
  "rgle_THPRXgold",
  "rgle_STCRXclear",
  "rgle_THCRXclear",
  "rgle_STBRXclear",
  "rgle_THBRXclear",
  "rgle_8Wwater",
  "rgle_8PWwater",
]);

export const LenseSchema = z.object({
  id: z.string(),
  name: z.string(),
  sku: LensSKUSchema,
  scenes: z.array(SceneSchema),
});
