import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@styles/globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  controls: React.ReactNode
  previews: React.ReactNode
}

export default function RootLayout({ controls, previews }: Readonly<Props>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} bg-background`}
      >
        <main className="w-full flex justify-start items-start">
          <aside className="w-[30%] border-r border-gray-200 h-screen">
            {controls}
          </aside>
          <section className="w-[70%] bg-background h-screen relative">
            {previews}
          </section>
        </main>
      </body>
    </html>
  );
}
